name: Compile Executables

on:
  push:
    paths:
      - 'src/main.py'
      - 'src/functions.py'
      - 'src/zcli.py'
      - 'src/zlm.py'

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile
        run: |
          ./dist/build.sh